import { DashboardTableColumn } from 'store';
import { TestStatus } from 'typesCustom/tests';

export const DASHBOARD_TABLE_COLUMN: DashboardTableColumn[] = [
  {
    name: 'deviceType',
    label: 'Name',
    visible: true,
    minWidth: 120,
    align: 'left',
    sortable: false,
  },
  {
    name: 'deviceId',
    label: 'Device ID',
    visible: true,
    minWidth: 120,
    align: 'left',
    sortable: true,
  },
  {
    name: 'ipAddress',
    label: 'Address',
    visible: true,
    minWidth: 120,
    align: 'left',
    sortable: true,
  },
  {
    name: 'softwareVersion',
    label: 'Software',
    visible: true,
    minWidth: 100,
    align: 'left',
    sortable: false,
  },
  {
    name: 'createdAt',
    label: 'Onboarded On',
    visible: true,
    minWidth: 150,
    align: 'left',
    sortable: false,
  },
  {
    name: 'lastExecutionStatus',
    label: 'Test Result',
    visible: true,
    minWidth: 120,
    align: 'left',
    sortable: false,
  },
  {
    name: 'interfaces',
    label: 'Interfaces',
    visible: true,
    minWidth: 100,
    align: 'left',
    sortable: false,
  },
  {
    name: 'availability',
    label: 'Availability',
    visible: true,
    minWidth: 100,
    align: 'left',
    sortable: true,
  },
  {
    name: 'usage',
    label: 'Usage',
    subLabel: '(Last 24 Hours)',
    visible: true,
    minWidth: 150,
    align: 'left',
    sortable: false,
  },
  {
    name: 'status',
    label: 'Status',
    visible: false,
    minWidth: 100,
    align: 'left',
    sortable: false,
  },
  {
    name: 'action',
    label: 'Action',
    visible: true,
    minWidth: 100,
    align: 'center',
    sortable: false,
  },
];

export const USER_DASHBOARD_TABLE = [
  {
    name: 'deviceType',
    label: 'Device',
    visible: true,
    minWidth: 80,
    align: 'left',
    sortable: true,
  },
  {
    name: 'buildId',
    label: 'Build',
    visible: true,
    minWidth: 80,
    align: 'left',
    sortable: true,
  },
  {
    name: 'duration',
    label: 'Duration',
    visible: true,
    minWidth: 80,
    align: 'left',
    sortable: false,
  },
  {
    name: 'testPlanName',
    label: 'Test Plan',
    visible: true,
    minWidth: 120,
    align: 'left',
    sortable: true,
  },
  {
    name: 'passed',
    label: 'Passed',
    visible: true,
    minWidth: 60,
    align: 'left',
    sortable: false,
  },
  {
    name: 'failed',
    label: 'Failed',
    visible: true,
    minWidth: 60,
    align: 'left',
    sortable: false,
  },
  {
    name: 'status',
    label: 'Status',
    visible: true,
    minWidth: 120,
    align: 'left',
    sortable: true,
  },
  {
    name: 'execution',
    label: 'Execution %',
    visible: true,
    minWidth: 100,
    align: 'left',
    sortable: false,
  },
];

export const STATE_LABEL = {
  [TestStatus.COMPLETED]: 'Passed',
  [TestStatus.FAILED]: 'Failed',
  [TestStatus.IN_PROGRESS]: 'In Progress',
  [TestStatus.NOT_EXECUTED]: 'In Progress',
  [TestStatus.QUEUED]: 'Queued',
  [TestStatus.CANCELLED]: 'Cancelled',
};
